/* ─── Torre de Hanói (P10) ─── */
/* ══════════════════════════════════════════════════════
   HANOI
══════════════════════════════════════════════════════ */
function switchTab(id){['py-rec','py-iter','cpp'].forEach(t=>{document.getElementById('tab-'+t).style.display=t===id?'block':'none';const btn=document.getElementById('tab-btn-'+t);if(t===id){btn.style.background='var(--code-bg)';btn.style.color='var(--accent)';}else{btn.style.background='var(--surface)';btn.style.color='var(--muted)';}});}
const DISK_COLORS=['#e74c3c','#e67e22','#f1c40f','#2ecc71','#1abc9c','#3498db','#9b59b6','#e91e63'];
let hanoiMoves=[],hanoiStep=0,hanoiTimer=null,hanoiPinos={A:[],B:[],C:[]},hanoiN=4;
function gerarRec(n,o,d,a,moves){if(n===1){moves.push([o,d]);return;}gerarRec(n-1,o,a,d,moves);moves.push([o,d]);gerarRec(n-1,a,d,o,moves);}
function gerarIter(n,o,d,a){const pilha=[{n,o,d,a}],moves=[];while(pilha.length){const{n:cn,o:co,d:cd,a:ca}=pilha.pop();if(cn===1){moves.push([co,cd]);continue;}pilha.push({n:cn-1,o:ca,d:cd,a:co});pilha.push({n:1,o:co,d:cd,a:ca});pilha.push({n:cn-1,o:co,d:ca,a:cd});}return moves;}
function iniciarHanoi(modo){if(hanoiTimer)clearInterval(hanoiTimer);hanoiN=+document.getElementById('hanoi-n').value;hanoiMoves=[];if(modo==='rec')gerarRec(hanoiN,'A','C','B',hanoiMoves);else hanoiMoves=gerarIter(hanoiN,'A','C','B');hanoiPinos={A:[],B:[],C:[]};for(let i=hanoiN;i>=1;i--)hanoiPinos.A.push(i);hanoiStep=0;document.getElementById('stat-n').textContent=hanoiN;document.getElementById('stat-total').textContent=hanoiMoves.length;document.getElementById('stat-atual').textContent=0;document.getElementById('stat-modo').textContent=modo==='rec'?'REC':'ITER';const log=document.getElementById('hanoi-log');log.innerHTML=`> ${modo==='rec'?'Recursivo':'Iterativo'} — n=${hanoiN}, ${hanoiMoves.length} movimentos...\n`;const speed=980-+document.getElementById('hanoi-speed').value;desenharHanoi();hanoiTimer=setInterval(()=>{if(hanoiStep>=hanoiMoves.length){clearInterval(hanoiTimer);log.innerHTML+=`> ✅ Concluído! ${hanoiMoves.length} movimentos.\n`;log.scrollTop=log.scrollHeight;return;}const[from,to]=hanoiMoves[hanoiStep];const disco=hanoiPinos[from].pop();hanoiPinos[to].push(disco);hanoiStep++;document.getElementById('stat-atual').textContent=hanoiStep;log.innerHTML+=`> [${hanoiStep}] disco ${disco}  ${from} → ${to}\n`;log.scrollTop=log.scrollHeight;desenharHanoi();},speed);}
function resetHanoi(){if(hanoiTimer)clearInterval(hanoiTimer);hanoiN=+document.getElementById('hanoi-n').value;hanoiPinos={A:[],B:[],C:[]};for(let i=hanoiN;i>=1;i--)hanoiPinos.A.push(i);hanoiStep=0;['stat-n','stat-total','stat-modo'].forEach(id=>document.getElementById(id).textContent='—');document.getElementById('stat-atual').textContent=0;document.getElementById('hanoi-log').innerHTML='> Reset. Pressione ▶ para iniciar.\n';desenharHanoi();}
function desenharHanoi(){const canvas=document.getElementById('hanoi-canvas');const W=canvas.offsetWidth||820,H=300;canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d');ctx.fillStyle='#0a0c10';ctx.fillRect(0,0,W,H);const baseY=H-28,pinoH=220,pinoW=7,baseW=W/4-30,maxN=hanoiN||4,discH=20,pinoX={A:W/4,B:W/2,C:3*W/4};ctx.fillStyle='#242836';ctx.fillRect(W/8,baseY,W*3/4,10);Object.values(pinoX).forEach(x=>{ctx.fillStyle='#3a3f52';ctx.fillRect(x-pinoW/2,baseY-pinoH,pinoW,pinoH);});['A','B','C'].forEach(p=>{ctx.fillStyle='#5dade2';ctx.font='bold 14px JetBrains Mono,monospace';ctx.textAlign='center';ctx.fillText(p,pinoX[p],baseY+22);ctx.fillStyle='#3a3f52';ctx.font='10px JetBrains Mono,monospace';ctx.fillText(hanoiPinos[p].length,pinoX[p],baseY-pinoH-6);});['A','B','C'].forEach(p=>{hanoiPinos[p].forEach((disco,idx)=>{const frac=disco/maxN,dw=Math.max(baseW*(0.25+0.75*frac),24),dy=baseY-(idx+1)*(discH+2),cor=DISK_COLORS[disco-1]||'#7f8c8d';ctx.fillStyle='rgba(0,0,0,0.35)';ctx.fillRect(pinoX[p]-dw/2+3,dy+3,dw,discH);ctx.fillStyle=cor;ctx.beginPath();ctx.roundRect(pinoX[p]-dw/2,dy,dw,discH,4);ctx.fill();ctx.fillStyle='rgba(0,0,0,0.8)';ctx.font='bold 11px JetBrains Mono,monospace';ctx.textAlign='center';ctx.fillText(disco,pinoX[p],dy+discH/2+4);});});}
