/* ─── Módulo Matrizes (P9) ─── */
/* ══════════════════════════════════════════════════════
   MATRICES (P9)
══════════════════════════════════════════════════════ */
let matA=[],matB=[];
function gerarMatrizes(){const M=+document.getElementById('mat-m').value,N=+document.getElementById('mat-n').value,P=+document.getElementById('mat-p').value;matA=Array.from({length:M},()=>Array.from({length:N},()=>Math.floor(Math.random()*9)+1));matB=Array.from({length:N},()=>Array.from({length:P},()=>Math.floor(Math.random()*9)+1));renderMatrizes(matA,matB,null,null,M,N,P);document.getElementById('matrix-info').style.display='none';}
function renderMatrizes(A,B,C,op,M,N,P){const d=document.getElementById('matrix-display');d.innerHTML='';d.appendChild(makeMat(A,`A [${M}×${N}]`,'#5dade2'));if(op){const sym=document.createElement('div');sym.textContent=op;sym.style.cssText='font-size:2em;font-weight:700;color:#7a8099;align-self:center;';d.appendChild(sym);}d.appendChild(makeMat(B,`B [${N}×${P}]`,'#5dade2'));if(C){const eq=document.createElement('div');eq.textContent='=';eq.style.cssText='font-size:2em;font-weight:700;color:#7a8099;align-self:center;';d.appendChild(eq);d.appendChild(makeMat(C,`C [${C.length}×${C[0].length}]`,'#27ae60',true));}}
function makeMat(data,label,borderColor,isResult){const wrap=document.createElement('div');wrap.style.cssText='text-align:center;';const lbl=document.createElement('div');lbl.textContent=label;lbl.style.cssText=`font-family:JetBrains Mono,monospace;font-size:12px;color:${borderColor};margin-bottom:8px;font-weight:700;`;wrap.appendChild(lbl);const tbl=document.createElement('table');tbl.style.cssText='border-collapse:collapse;margin:auto;';data.forEach(row=>{const tr=document.createElement('tr');row.forEach(val=>{const td=document.createElement('td');td.textContent=val;td.style.cssText=`width:36px;height:36px;text-align:center;border:1px solid #242836;font-family:JetBrains Mono,monospace;font-size:13px;background:${isResult?'rgba(39,174,96,0.12)':'#1a1e28'};color:${isResult?'#98c379':'#e8eaf0'};`;tr.appendChild(td);});tbl.appendChild(tr);});wrap.appendChild(tbl);return wrap;}
function calcularSoma(){if(!matA.length){alert('Gere as matrizes primeiro!');return;}const M=matA.length,N=matA[0].length,info=document.getElementById('matrix-info');if(M!==matB.length||N!==matB[0].length){info.style.display='block';info.style.borderColor='#e74c3c';info.innerHTML=`❌ Soma inválida: A[${M}×${N}] ≠ B[${matB.length}×${matB[0].length}]`;return;}const C=matA.map((row,i)=>row.map((v,j)=>v+matB[i][j]));renderMatrizes(matA,matB,C,'+',M,N,matB[0].length);info.style.display='block';info.style.borderColor='#27ae60';info.innerHTML=`✅ Soma A + B — <strong>O(M·N) = O(${M}×${N}) = O(${M*N} operações)</strong>`;}
function calcularMult(){if(!matA.length){alert('Gere as matrizes primeiro!');return;}const M=matA.length,N=matA[0].length,P=matB[0].length,info=document.getElementById('matrix-info');if(N!==matB.length){info.style.display='block';info.style.borderColor='#e74c3c';info.innerHTML=`❌ Multiplicação inválida: colunas de A (${N}) ≠ linhas de B (${matB.length}).`;return;}const C=Array.from({length:M},()=>Array(P).fill(0));for(let i=0;i<M;i++)for(let j=0;j<P;j++)for(let k=0;k<N;k++)C[i][j]+=matA[i][k]*matB[k][j];renderMatrizes(matA,matB,C,'×',M,N,P);info.style.display='block';info.style.borderColor='#f39c12';info.innerHTML=`✅ Multiplicação A × B — <strong>O(M·N·P) = O(${M}×${N}×${P}) = O(${M*N*P} operações)</strong>`;}
